version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.7.7
    container_name: jellyfin
    #user: uid:gid
    #network_mode: "host"
    volumes:
      - ./configs/configJellyfin:/config
      - ./media:/media #Or wherever you place your media
    restart: "unless-stopped"
    ports:
      - 8096:8096
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096"]

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    #depends_on:
    #  - vpn
    #network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - ./configs/configDeluge:/config
      - ./media/shows:/media/shows # Directory where your TV Shows are placed
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/Brussels 
      - UMASK=002
      - DELUGE_LOGLEVEL=error
    ports:
      - 8112:8112
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8112"]   

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    #network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./configs/configSonarr:/config
      - ./media/shows:/media/shows # Directory where your TV Shows are placed
      - ./media/movies:/media/movies # Directory where your movies are placed
    restart: unless-stopped
    ports:
      - 8989:8989
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]

 