version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: uid:gid
    network_mode: "host"
    volumes:
      - Docker/jellyfin/config:/config
      - Docker/jellyfin/cache:/cache
      - mkdir Docker/jellyfin/media:/media
    restart: "unless-stopped"