version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.7.7
    container_name: jellyfin
    #user: uid:gid
    #network_mode: "host"
    volumes:
      - ./config:/config
      - ./volumes/jellyfin:/media #Or wherever you place your media
    restart: "unless-stopped"
    ports:
      - 8096:8096
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096"]

  sonarr:
    image: linuxserver/sonarr:amd64-0.6.1399
    container_name: sonarr
    #network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./configSonarr:/config
     # - /media/DATA1/TorrentTemp:/media/DATA1/TorrentTemp # Temporary directory for downloads
      - ./volumes/jellyfin/media/shows:/media/shows # Directory where your TV Shows are placed
      - ./volumes/jellyfin/media/movies:/media/movies # Directory where your movies are placed

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]    