version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: uid:gid
    network_mode: "host"
    volumes:
      - /home/vagrant/Docker/jellyfin/config:/config
      - /home/vagrant/Docker/jellyfin/cache:/cache
      - /home/vagrant/Docker/jellyfin/media:/media
    restart: "unless-stopped"
    ports:
      - 8096:8096