version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.7.7
    container_name: jellyfin
    #user: uid:gid
    #network_mode: "host"
    volumes:
      - ./configs/configJellyfin:/config
      - ./media:/media # Or wherever you place your media
    restart: "unless-stopped"
    ports:
      - 8096:8096
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096"]

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    depends_on:
      - openvpn
    network_mode: "service:openvpn"
    restart: unless-stopped
    volumes:
      - ./configs/configDeluge:/config
      - ./media/shows:/media/shows # Directory where your TV Shows are placed
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/Brussels 
      - UMASK=002
      - DELUGE_LOGLEVEL=error
   # ports:
    #  - 8112:8112
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8112"]   

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:openvpn"
    depends_on:
      - openvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./configs/configSonarr:/config
      - ./media/shows:/media/shows # Directory where your TV Shows are placed
      - ./media/movies:/media/movies # Directory where your movies are placed
    restart: unless-stopped
   # ports:
    #  - 8989:8989
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]

  radarr:
      image: linuxserver/radarr:latest
      container_name: radarr
      network_mode: "service:openvpn"
      depends_on:
      - openvpn
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Brussels
      volumes:
        - ./configs/configRadarr:/config
       # - /media/DATA1/:/media/DATA1/
        - ./media/shows:/media/shows # Directory where your TV Shows are placed
        - ./media/movies:/media/movies # Directory where your movies are placed
      restart: unless-stopped
     # ports:
      #  - 7878:7878
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:7878"]

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: "service:openvpn"
    depends_on:
      - openvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./configs/configBazarr:/config
    # - /media/DATA1/:/media/DATA1/
      - ./media/shows:/media/shows # Directory where your TV Shows are placed
      - ./media/movies:/media/movies # Directory where your movies are placed
    restart: unless-stopped
   # ports:
    #  - 6767:6767
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767"]

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:openvpn"
    depends_on:
      - openvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./configs/configJackett:/config
    restart: unless-stopped
   # ports:
    #  - 9117:9117
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9117"]

  openvpn:
    container_name: openvpn
    image: dperson/openvpn-client:latest
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: 'GMT'
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./configs/configVPN/OpenVPN:/vpn
    command: '-r 192.168.0.0/24 -r 172.16.0.0/12 -f 1198 -p 51735' # CHANGE THIS PORT FOR NEW PORT FORWARD REGION
    ports:
      - 58846:58846
      - 8112:8112
      - 8989:8989
      - 7878:7878
      - 6767:6767
      - 9117:9117
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - default
    dns:
      - 1.1.1.1
      - 1.0.0.1