# Workflow that tests Docker configuration

name: Test Docker containers

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run 'docker-compose up -d'
      run: docker-compose up -d

    - name: Run 'docker ps -a'
      run: docker ps -a