name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install VirtualBox
      run: |
        sudo apt-get install virtualbox
    
    - name: Install Vagrant
      run: |
        wget https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
        sudo apt install ./vagrant_2.2.14_x86_64.deb

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
  
    - name: Show Vagrant version
      run: vagrant --version

    - name: Install docker-compose plugin
      run: vagrant plugin install vagrant-docker-compose
      
    - name: Run vagrant up
      run: vagrant up

  #  - name: ssh into box after boot
  #    run: vagrant ssh -c "echo 'hello world!'"
