# Workflow that tests Vagrant configuration

name: Test Vagrant VM & Docker containers

on: [push]

jobs:
  vagrant:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
  
    - name: Show Vagrant version
      run: vagrant --version

    - name: Install docker-compose plugin
      run: vagrant plugin install vagrant-docker-compose # Only for this workflow
      
    - name: Run 'vagrant up'
      run: vagrant up

    - name: SSH into VM & check Docker containers
      run: vagrant ssh -c "docker ps -a"
